### ISSUE TITLE
Permissions issue during `docker-compose up`

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/cloud-pricing-api#103]
A user is running into an issue in step number 5 of the readme. When they run 'docker-compose up' they get the attached error.

docker version : 20.10.7
`docker-compose version : v2.0.1
`sestatus` : disabled
OS: Amazon Linux
AWS AMI I'd: ami-03ab7423a204da002

![screen](https://user-images.githubusercontent.com/638577/136954478-35c186f2-f009-4cad-ae29-f5f1d7fa9119.jpg)

**Comment by amitlalg** [comment]
I got same error after updating my docker compose file

![image](https://user-images.githubusercontent.com/37605691/143109713-7fd7bb41-d0cb-4871-ad0f-a7c43260929d.png)

**Comment by alikhajeh1** [comment]
@amitlalg can you please try this workaround until the next release:
1. `rm -rf data/.gitkeep`
2. remove the 3 occurrences of the following from the docker-compose.yml: 
```
volumes:
      - ./data:/usr/src/app/data
```
3. `docker-compose build`
4. `docker-compose up`

**Comment by amitlalg** [comment]
> @amitlalg can you please try this workaround until the next release:
> 
> 1. `rm -rf data/.gitkeep`
> 2. remove the 3 occurrences of the following from the docker-compose.yml:
> 
> ```
> volumes:
>       - ./data:/usr/src/app/data
> ```
> 
> 3. `docker-compose build`
> 4. `docker-compose up`

I fixed by changing permission to 777 to cloud-api directory

**Comment by aliscott** [comment]
This issue has been fixed in https://github.com/infracost/cloud-pricing-api/pull/120 and released in v0.3.2.
