### ISSUE TITLE
Problems Deploying to ECS

### ISSUE THREAD

**Issue by samdjudd** [infracost/cloud-pricing-api#119]
I am unable to deploy to ECS using the docker-compose.yml file. Is deployment using the helm chart and Kubernetes the only option for hosting the cloud pricing API in AWS?

<img width="860" alt="Screen Shot 2021-11-10 at 9 26 54 AM" src="https://user-images.githubusercontent.com/43186441/141152499-1de87b3a-d9e4-464a-a8ee-b332885e08a1.png">

**Comment by alikhajeh1** [comment]
@samdjudd thanks for creating and closing the issue! I'm curious what was the problem?

**Comment by samdjudd** [comment]
@alikhajeh1 Still haven't figured out the issue, I just didn't feel like I had enough background info to create one. I am still testing a few different theories.

**Comment by alikhajeh1** [comment]
@samdjudd no problems at all, we have users that run that docker-compose on EC2 and we'd be happy to help with any issues on ECS - feel free to keep posting here or [join our Slack](https://www.infracost.io/community-chat) if you prefer chat

**Comment by samdjudd** [comment]
@alikhajeh1 Great! Thank you, I will reach on Slack.

**Comment by alikhajeh1** [comment]
@samdjudd we released a new version that where we removed the profiles from docker-compose, can you please help us by testing it on ECS? Please also check that your `docker --version` is newer than 17.09.0.
