### ISSUE TITLE
docker-compose up issue

### ISSUE THREAD

**Issue by amitlalg** [infracost/cloud-pricing-api#121]
Hello!
On step#5, issue happening -
![image](https://user-images.githubusercontent.com/37605691/143077684-c6392e2f-6af8-48c3-8257-ac1c10a27ba3.png)

**Comment by aliscott** [comment]
I think `start_period` was added in the compose file format v3.4 ([according to here](https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck)) which needs the docker engine 17.09.0+ ([according to here](https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix)). I'm not sure when `profiles` was added.

We should work out what is the minimum version we support and add it to the docs/update the version header in the compose file.

**Comment by vdmgolub** [comment]
@aliscott The `profiles` option has been added in docker-compose 1.28 ([from here](https://forums.docker.com/t/unsupported-config-option-for-services-profiles/103767))

**Comment by amitlalg** [comment]
Here is my docker version 
s4hanadocker:~/cloud-pricing-api # docker --version
**Docker version 20.10.6-ce, build 8728dd246c3a**
s4hanadocker:~/cloud-pricing-api #

**Comment by amitlalg** [comment]
Here is my docker version -

s4hanadocker:~/cloud-pricing-api # docker --version
Docker version 20.10.6-ce, build 8728dd246c3a
s4hanadocker:~/cloud-pricing-api #

**Comment by amitlalg** [comment]
> @aliscott The `profiles` option has been added in docker-compose 1.28 ([from here](https://forums.docker.com/t/unsupported-config-option-for-services-profiles/103767), [release notes](https://docs.docker.com/compose/release-notes/#1280))

my docker version is 
**Docker version 20.10.6-ce, build 8728dd246c3a**

**Comment by aliscott** [comment]
If you're using an older docker-compose version and not able to upgrade, then the quickest fix for now would be to remove the `profiles`, and `start_period` lines from the docker-compose file and try that.

**Comment by amitlalg** [comment]
> 

Thanks, I would request you guys to add a prerequisite section (similar to the helm chart)
What's the recommended version for this API to work?
https://github.com/infracost/helm-charts/tree/master/charts/cloud-pricing-api#prerequisites

**Comment by aliscott** [comment]
docker-compose v1.28 is the minimum. Thanks, I've added it to the list to test with other versions and add a prerequisite section before the next release, which should be later this week.

**Comment by amitlalg** [comment]
> docker-compose v1.28 is the minimum. Thanks, I've added it to the list to test with other versions and add a prerequisite section before the next release, which should be later this week.

Thank you for the quick input! Appreciated!

**Comment by amitlalg** [comment]
I have updated the docker-compose ver. to 1.29 now! successfully ran the docker up command but now receiving "permission denied" error on /usr/src/app/data/products path. I created this manually and re-run but no success!  Please help! thanks


![image](https://user-images.githubusercontent.com/37605691/143111496-faaa4778-c87f-47e4-91ba-f6e55ca9c811.png)

**Comment by amitlalg** [comment]
Fixed...

**Comment by aliscott** [comment]
@amitlalg, I've updated this to work with older versions now and started a prerequisite section for the docker compose file in https://github.com/infracost/cloud-pricing-api/pull/122. This has been released in v0.3.2. Thanks for helping investigate this.

**Comment by amitlalg** [comment]
Thanks so much! Happy thanksgiving!
