### ISSUE TITLE
Wrong pricing for AWS Step Functions

### ISSUE THREAD

**Issue by leonardobiffi** [infracost/cloud-pricing-api#186]
In AWS pricing page: https://aws.amazon.com/pt/step-functions/pricing/
```
Price per 1,000 state transitions
$0.025

```

In infracost output for `aws_sfn_state_machine`
```
+ module.state_machine_simple.aws_sfn_state_machine.sfn_state_machine
  Monthly cost depends on usage

    + Transitions
      Monthly cost depends on usage
        +$0.00005 per 1K transitions
```

**Comment by tim775** [comment]
Thanks!

**Comment by tim775** [comment]
The pricing data is correct, but the CLI isn't using "1000" as the unit multipler so the quantities were throw off.  The fix is in https://github.com/infracost/infracost/pull/1509.

**Comment by leonardobiffi** [comment]
Wow, that was fast
Awesome @tim775
