### ISSUE TITLE
Wrong or empty pricing for GCP Spot

### ISSUE THREAD

**Issue by Craftikdev** [infracost/cloud-pricing-api#230]
In GCP pricing:
![test1](https://user-images.githubusercontent.com/11787189/179251385-6e8b8242-1aba-44a2-aed0-76b26a1b8312.PNG)

In infracost api output:
![test2](https://user-images.githubusercontent.com/11787189/179251390-72ae5632-b215-44ad-bda7-dbf7a56ea947.PNG)

GCP changed description for spot instances, Preemptible to Spot Preemptible https://cloud.google.com/skus/sku-groups/spot-preemptible-e2-vms.

Need modify regex:
https://github.com/infracost/cloud-pricing-api/blob/6483e8c8b42c04ec024abc0ef3d0ee56537e7695/src/scrapers/gcpMachineTypes.ts#L229

**Comment by hugorut** [comment]
Thanks @Craftikdev, for raising this issue. We've put a fix into the cloud pricing API to resolve the Spot prices. The correct prices should be synced when we next scrape GCP. This is scheduled for early tomorrow AM (GMT).
