### ISSUE TITLE
attributeFilters documentation

### ISSUE THREAD

**Issue by vivekkarne** [infracost/cloud-pricing-api#352]
What key values can be used for the attributeFilters field? Is there any documentation for each of the cloud providers which points to what filters I can use??

**Comment by vdmgolub** [comment]
Hello!

Thank you for creating the issue! :) May I also ask you what is your use case? Why do you need to query the cloud pricing API?

The `attributes` content depends on a specific service/resource (for example, instance type is relevant to EC2, but doesn't make sense for other resources) and has the same fields as the cloud vendor's pricing APIs. We clarify this in [our docs](https://www.infracost.io/docs/cloud_pricing_api/overview/#concepts):

> The API has [two main types](https://github.com/infracost/cloud-pricing-api/blob/master/src/db/types.ts): Products and Prices. Each product can have many Prices. This simple high-level schema provides flexibility to model the exact values that the cloud vendor APIs return at the same time as having useful top-level product filters. The values returned by the API are the same ones that the cloud vendors return in their APIs.

Each cloud provider has their documentation for the pricing APIs. However, they have thousands of SKUs, each with its distinct structure, which can be changed with the new pricing update. So, having such documentation would be another challenge on its own. 

Querying cloud-pricing-api's SQL database is the quickest way to find the attributes you need. This requires installing CPAPI and using SQL queries, but having the raw data gives you up-to-date information. We have a dedicated section in our CLI contribution guide that describes such a search process.

Please take a look: https://github.com/infracost/infracost/blob/master/contributing/add_new_resource_guide.md#price-search.
And here you can find the deployment instructions: https://github.com/infracost/cloud-pricing-api/blob/master/CONTRIBUTING.md.

Please let me know if you have more questions :)

**Comment by vivekkarne** [comment]
Thank you for the response, I will look into this. Our use-case is to have a terraform node-pool set to the cheapest instance given certain criteria like vcpu count, memory, and cpu architecture to start out with. I was trying to explore your API since our terraform architecture would be deployed on the 3 major cloud providers. 

I think this issue https://github.com/infracost/cloud-pricing-api/issues/327 is pretty similar to what we are looking for as well. I just wanted to hack around and tailor it to our needs.

**Comment by vdmgolub** [comment]
Thank you for sharing! Querying the database directly is the fastest way to determine the filter attributes. I'll be closing this issue for now. Feel free to reopen if you need more help :)

**Comment by vdmgolub** [comment]
@lariskovski Hello! Unfortunately, the GCP pricing's SKUs are not straightforward, and, as you notice, `tier` is not available. CLI splits the tier string into pieces and uses them to form attributes' value. Your script will have to do something similar to retrieve the prices. For example, for your tier `db-custom-1-3840` we would have the following components:
1. CPU, with the attribute filter generated as `{ key: "description", value_regex: "/<db type>: <availability type> - vCPU/" }`. See the [CLI code](https://github.com/infracost/infracost/blob/master/internal/resources/google/sql_database_instance.go#L153) for reference (it is Go code, but should give an idea).
2. Memory, with attribute filter generated as `{ key: "description", value_regex: "/<db type>: <availability type> - RAM/" }`. [CLI code](https://github.com/infracost/infracost/blob/master/internal/resources/google/sql_database_instance.go#L131).

Notice that we use `value_regex` to match the description values. Here are the options for these filters: https://github.com/infracost/infracost/blob/master/internal/resources/google/sql_database_instance.go#L230-L247

Hope this helps :)
