### ISSUE TITLE
API not working with gcp and azure filters

### ISSUE THREAD

**Issue by naveen-420** [infracost/cloud-pricing-api#424]
Hi Team,

I tried fetching data for GCP and AZURE with cloud pricing api and the response is coming as empty list. The same API is working for AWS. Please find the screenshot below. 

I'm using a valid API key and below example is from examples directory.

![image](https://github.com/infracost/cloud-pricing-api/assets/71978079/8cc4f05f-ed7e-4594-9d0b-aa3b27052b8b)

**Comment by devopsbarista** [comment]
Hey @naveen-420, try removing or changing some of the `attributeFilters`; it should work just fine. In this particular Azure example, the issue is with the `meterName`, there are no matching results for `P60 Disks`, hence you're getting an empty list. Hope it helps.

**Comment by naveen-420** [comment]
Thanks for your response. closing the ticket as API is working fine and issue is due to no matching results
