### ISSUE TITLE
Status check route

### ISSUE THREAD

**Issue by rasta-rocket** [infracost/cloud-pricing-api#51]
Hello 👋 

From an infra point of view, it would be nice to have a route in the API that answer 2xx HTTP return code, to check if the service is up or not (ex: /status, /health, etc).

Nice work by the way 😉 

Thx

**Comment by alikhajeh1** [comment]
Thanks! Great point, we've been heads-down on the CLI... this is an obvious thing we should add. Should be simple.

**Comment by alikhajeh1** [comment]
@rasta-rocket, @simon-jt and @PatMyron just FYI that we're going to focus on improving the self-hosting experience next :) @aliscott created https://github.com/infracost/cloud-pricing-api/issues/52 and we'd love to get your feedback on that. I'll leave this GH issue open as we can address it as part of that epic.

**Comment by alikhajeh1** [comment]
Hey everyone, please see https://www.infracost.io/blog/jul-2021-update for this and other improvements we shipped. A `/health` route has been added (that is used by Docker compose and Helm charts for healthcheck), and the `/` homepage shows stats, see https://www.infracost.io/docs/cloud_pricing_api/self_hosted#stats-page for a screenshot.

Please let us know how you get on or have any feedback.

**Comment by rasta-rocket** [comment]
You guys rock 🤩 🚀 🤘
