### ISSUE TITLE
Improve self-hosting of Cloud Pricing API

### ISSUE THREAD

**Issue by aliscott** [infracost/cloud-pricing-api#52]
## Background

Currently it is difficult for users to deploy the Cloud Pricing API on their own infrastructure. We have had users spend significant time getting it up and running and others who have given up.

## Status Quo

* The Cloud Pricing API has documentation for running it locally, but nothing for deploying it in a cloud environment.
* The Cloud Pricing API uses MongoDB to store the products and prices.
* The Cloud Pricing API has scripts for updating the prices from the cloud vendors using their APIs. These download a lot of data and take a significant time (>2 hours) to run.

## What should we do next?

We should improve the self-hosting experience of the Cloud Pricing API and the documentation around it.

As part of this we should answer the following:
1. Which cloud providers / services we will support deploying on?
2. Which backend database we use/ Currently we use MongoDB.
3. How we handle the update jobs? Does each instance of the Cloud Pricing API run the updaters to hit the cloud provider prices directly, or do we offer a service to allow this to be done quicker?

## Over to you

We'd appreciate feedback, especially if you have gone through the process of deploying or trying to deploy this

**Comment by simon-jt** [comment]
Hi since many cloud providers have their own managed kubernetes it would be nice to focus on k8s deployment for example with a helm-chart to deploy the cloud pricing api. It would help for both cloud and non cloud local hosting since kubernetes can be deployed everywhere, what do you think ?

**Comment by alikhajeh1** [comment]
@simon-jt we've heard from a few users who are already deploying this on K8s so I think a helm chart makes sense. If you are already self-hosting this, do you remember what was most painful about it?

**Comment by oakimov** [comment]
De-coupling database and using Cosmos DB with Mongo DB API on Azure instead of MongoDB as part of the k8s deployment, or native cloud database deployments would make sense too (RDS, DynamoDB on AWS, BigQuery / CloudSQL on GCP) - provisioned by terraform. If I had a vote, I'd say go RDS / SQL route and the rest of components as helm chart.

**Comment by aliscott** [comment]
Thanks for the feedback so far @simon-jt and @oakimov 😄 . Here's some updates on what we have planned initially to help with the self-hosting. It would be great to hear any more feedback you have.

**DB**

We are looking at switching the backend from MongoDB to PostgreSQL since all the major cloud vendors have hosted options for this.

**Deployment**

We are implementing an official Helm chart for the Cloud Pricing API that will deploy the API and a cronjob for updating the prices. By default it will deploy a PostgreSQL pod but can also be configured to use an external PostgreSQL instance, like AWS RDS.

We will also support an official docker-compose file.

**Jobs**

To make the jobs quicker and more robust we are looking at adding a command that will pull a dump of up-to-date pricing data from our S3 bucket. This should increase the time it takes to update the prices from >2 hours to a couple of minutes.

**Comment by simon-jt** [comment]
> Hi since many cloud providers have their own managed kubernetes it would be nice to focus on k8s deployment for example with a helm-chart to deploy the cloud pricing api. It would help for both cloud and non cloud local hosting since kubernetes can be deployed everywhere, what do you think ?

As long as the docker image is available to pull from a registry I think you pointed out all other pain points I saw ;)

**Comment by alikhajeh1** [comment]
Thanks @simon-jt - noted! We'll test the update job and recommend pod request/limits.

**Comment by hassankhosseini** [comment]
Hey everyone! Thank you all for your input into this ticket and the 👍🏽s

We are now live with self-hosting. [Ali wrote a blog](https://www.infracost.io/blog/jul-2021-update) about it, and here are the docs: [https://www.infracost.io/docs/cloud_pricing_api/self_hosted](https://www.infracost.io/docs/cloud_pricing_api/self_hosted)

We've also written a section about migrating from old versions in the docs. Please let us know if you have any issues or questions about either using this, or migrating from an older version.

Cheers! 🚀🎉
