### ISSUE TITLE
Add Azure Prices

### ISSUE THREAD

**Issue by moredure** [infracost/cloud-pricing-api#8]

**Comment by JJediny** [comment]
Docs: `https://docs.microsoft.com/en-us/rest/api/cost-management/retail-prices/azure-retail-prices`
Endpoint (REST): `https://prices.azure.com/api/retail/prices`

**Comment by aliscott** [comment]
@JJediny thanks. @DanielMabbett has a work-in-progress fork that uses the Azure Retail API, so watch this space!

**Comment by DanielMabbett** [comment]
PR for visibility:
https://github.com/infracost/cloud-pricing-api/pull/31

**Comment by aliscott** [comment]
Thanks everyone! This was added in #31 and #40 and Infracost support has also been release. See https://github.com/infracost/infracost/issues/64#issuecomment-855984059 for more details.
